---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: demo-nginx
  name: demo-nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: demo-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: demo-nginx
    spec:
      containers:
      - image: theopenbit/rpi-demo-nginx
        imagePullPolicy: Always
        name: demo-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo-nginx
  name: demo-nginx
  namespace: default
  resourceVersion: "5268"
spec:
  ports:
  - nodePort: 30275
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: demo-nginx
  sessionAffinity: None
  type: NodePort
